# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Gravilux' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Gravilux

  pod 'Firebase/Analytics'

end
